CREATE TYPE STATUS_TYPE AS ENUM ('NEW', 'ACTIVE', 'DEACTIVATED');

DROP TABLE IF EXISTS CAMPAIGN;
CREATE TABLE CAMPAIGN
(
    id     uuid DEFAULT RANDOM_UUID() NOT NULL PRIMARY KEY ,
    name   varchar(30) NOT NULL,
    status STATUS_TYPE NOT NULL default 'NEW'
);

DROP TABLE IF EXISTS SCENARIOS;
CREATE TABLE SCENARIOS
(
    id     uuid DEFAULT RANDOM_UUID() NOT NULL PRIMARY KEY,
    name   varchar(30) NOT NULL,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    campaign_id uuid REFERENCES CAMPAIGN(id)
);